### ISSUE TITLE
Bug: reload command not working

### ISSUE THREAD

**Issue by angelyurii** [boxsux/cardboardbox#1]
**Desperately needing to fix this, putting this issue here so others can respond with suggestions.**

Function in [functions.js](https://github.com/rhearmas/cardboardbot/blob/master/modules/functions.js) used in the [reload command](https://github.com/rhearmas/cardboardbot/blob/master/commands/Utility/reload.js) need to be fixed.

Command works once but then returns this error when trying to use **/reload** on the same command:

`TypeError: Cannot read property 'parent' of undefined at Client.client.reloadCommand (C:\Users\criti\Repositories\cardboardbot\modules\functions.js:118:27)`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by samsamson33** [comment]
@rhearmas are you sure the `/reload` command reloads the file the first time it's run? When I try it locally, I get the error below, then the second time, `/reload` fails because it tries to unload a command that wasn't loaded.

![image](https://user-images.githubusercontent.com/35579293/71300067-c9a32900-235f-11ea-97a8-f0e9acd963f9.png)

Either way, the error you are getting is from `mod` being `undefined`, which means ``require.cache[require.resolve(`../commands/${command.help.category}/${command.help.name}`)];`` is undefined too.

**Comment by angelyurii** [comment]
@samsamson33 Huh, okay. I'm attempting to modify the code for the command to see if I can get it to work that way.

**Comment by angelyurii** [comment]
Managed to fix it by making the function unnecessary and rewriting the code a bit. Thanks for your input! (https://github.com/rhearmas/cardboardbot/commit/a32079a4f0714927ac7bb32566e74bd2591f3488)
